
server:
  port : ${PORT:8988}

spring:
  application:
    name: "db-api-learning"
  datasource:
    url : jdbc:postgresql://localhost:5432/myapp_db?currentSchema=public
    username: sokmean
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
    liquibase-schema: public
  jpa:
    hibernate:
      ddl-auto : validate
    show-sql: true
    properties:
      hibernate:
        format_sql=true: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

logging:
  level:
    liquibase: INFO
    org.hibernate:
      SQL=DEBUG:
        type.descriptor.sql.BasicBinder : "TRACE"

jwt:
  key: your-256-bit-secret-key-change-this-in-production-make-it-very-long-and-random
  access-token-expiration: 60000 #3600000 #1h
  refresh-token-expiration: 86400000 #24h
